### ISSUE TITLE
Is TREK-150/sequences.txt missing?

### ISSUE THREAD

**Issue by kumatheworld** [matteo-dunnhofer/TREK-150-toolkit#1]
I got the following error when I executed `python download.py`.
```sh
Checking and downloading TREK-150. This process might take a while...
100% [......................................................] 764679 / 764679Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kumatheworld/datasets/TREK-150-toolkit/toolkit/datasets/trek150.py", line 28, in __init__
    self._download(self.root_dir)
  File "/Users/kumatheworld/datasets/TREK-150-toolkit/toolkit/datasets/trek150.py", line 83, in _download
    assert os.path.exists(seqs_file)
AssertionError
```
I have successfully downloaded `TREK-150-annotations.zip` and it was extracted to `TREK-150-annotations/`, but it seems that `TREK-150/sequences.txt` is still missing.
```sh
$ ls TREK-150/
TREK-150-annotations     TREK-150-annotations.zip __MACOSX
```

**Comment by matteo-dunnhofer** [comment]
Thanks @kumatheworld 

There was an issue with the archive containing the annotations. I corrected it and now the dataset download should work. Let me know.

**Comment by kumatheworld** [comment]
It is now working. Thanks!
