### ISSUE TITLE
Downloading Trek150

### ISSUE THREAD

**Issue by MsAnitaAli** [matteo-dunnhofer/TREK-150-toolkit#6]
As indicated in ReadMe that 
The full TREK-150 dataset can be built just by running

pip install got10k
git clone https://github.com/matteo-dunnhofer/TREK-150-toolkit
cd TREK-150-toolkit
python download.py

I expect that it will download video sequences along with annotations, but it terminates by simply saying this.
Checking and downloading TREK-150. This process might take a while...
100% [..........................................................................] 1909911 / 1909911Processing video sequence P03-P03_02-612 [1/150]

        Extracting annotation to ./TREK-150...
Traceback (most recent call last):
  File "C:\Users\Administrator\desktop\githubclones\trek150\trek-150-toolkit\download.py", line 3, in <module>
    dset = TREK150('./TREK-150')
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\desktop\githubclones\trek150\trek-150-toolkit\toolkit\datasets\trek150.py", line 28, in __init__
    self._download(self.root_dir)
  File "C:\Users\Administrator\desktop\githubclones\trek150\trek-150-toolkit\toolkit\datasets\trek150.py", line 122, in _download
    frame_idxs = np.loadtxt(os.path.join(seq_dir, 'frames.txt'), delimiter='\n', dtype=np.uint64)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\numpy\lib\npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\numpy\lib\npyio.py", line 1016, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
TypeError: control character 'delimiter' cannot be a newline (`\r` or `\n`).

**Issue 1:** 
It just downloads information about 1 video ( P03-P03_02-612).
**Issue 2:** 
It is just downloading annotations, not the  videos. 

Kindly help me.

**Comment by MsAnitaAli** [comment]
Although, I have  alternatively downloaded  it from VS code , but still no video sequence is downloaded. Only annotations and meta data have been downloaded.

**Comment by matteo-dunnhofer** [comment]
That error is probably related to a newer version of numpy. Try to downgrade numpy to a previous version.

**Comment by MsAnitaAli** [comment]
@matteo-dunnhofer 
Thank you so much. but I have not created any virtual environment for downloading data. I will try it from venv. Can you mention specific older numpy version?

**Comment by matteo-dunnhofer** [comment]
Code should run fine with a numpy version lower than 1.23.0.

**Comment by MsAnitaAli** [comment]
@matteo-dunnhofer 
Thank you so much . I will try and update you. I will close the issue in case of success.
