### ISSUE TITLE
HTTP error 400 when attempting to download

### ISSUE THREAD

**Issue by julyanghar** [matteo-dunnhofer/TREK-150-toolkit#7]
Checking and downloading TREK-150. This process might take a while...
Processing video sequence P03-P03_02-612 [1/150]
        Annotation already extracted!

        Downloading EK video to ./TREK-150\P03_02.MP4...
Traceback (most recent call last):
  File "download.py", line 3, in <module>
    dset = TREK150('./TREK-150')
  File "D:\slowfast\TREK-150-toolkit\toolkit\datasets\trek150.py", line 28, in __init__
    self._download(self.root_dir)
  File "D:\slowfast\TREK-150-toolkit\toolkit\datasets\trek150.py", line 136, in _download
    download(url_ek, mp4_file)
  File "D:\slowfast\TREK-150-toolkit\toolkit\utils\ioutils.py", line 19, in download
    return wget.download(url, out=filename)
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\site-packages\wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\julya\anaconda3\envs\SlowFast\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400:

I modified the version of numpy from 1.24 to1.22. But I got that issue.

**Comment by matteo-dunnhofer** [comment]
Hi @julyanghar 

that issue seems related to the server. Try downloading again at a later time.

**Comment by julyanghar** [comment]
Could it be related to the proxy setting? I can access data.bris.ac.uk using chrome with vpn. Usually it is impossible to access some websites without vpn since I am in China.

**Comment by julyanghar** [comment]
I tired to download using a cloud server and it worked. It might have something to do with the proxy setting. But I don't know how to use proxy with wget.download().

**Comment by matteo-dunnhofer** [comment]
Yes, it might be related to that. Other people downloading from China had a similar issue.

**Comment by julyanghar** [comment]
Is it possible to download it with proxy?

**Comment by matteo-dunnhofer** [comment]
Drop me an e-mail at matteo.dunnhofer@uniud.it and I will give further instructions
